-- LabelM — invoice_payments table, audit, RLS.
--
-- Design
--   * Records money received against an invoice. Payment records are
--     financial: any active member may view and record, but only owner/admin
--     may update or delete them.
--   * payment_mode is a fixed enum: cash, upi, bank_transfer, cheque.

-- ---------------------------------------------------------------------------
-- Enum type (no-op if it already exists)
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'payment_mode') then
    create type public.payment_mode as enum ('cash', 'upi', 'bank_transfer', 'cheque');
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- Table
-- ---------------------------------------------------------------------------
create table if not exists public.invoice_payments (
  id           integer generated by default as identity primary key,
  invoice_id   integer not null references public.invoices (id) on delete cascade,
  amount       numeric(12,2) not null check (amount > 0),
  payment_date date not null,
  payment_mode public.payment_mode not null,
  notes        text,
  received_by  uuid references public.employees (id) on delete set null,
  created_at   timestamptz not null default now()
);

create index if not exists invoice_payments_invoice_idx
  on public.invoice_payments (invoice_id);

-- ---------------------------------------------------------------------------
-- received_by stamping on insert
-- ---------------------------------------------------------------------------
create or replace function public.invoice_payments_set_received_by()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.received_by = auth.uid();
  return new;
end;
$$;

drop trigger if exists invoice_payments_set_received_by on public.invoice_payments;
create trigger invoice_payments_set_received_by
  before insert on public.invoice_payments
  for each row
  execute function public.invoice_payments_set_received_by();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.invoice_payments enable row level security;

-- Read: any active member (staff can view payment history).
drop policy if exists invoice_payments_select on public.invoice_payments;
create policy invoice_payments_select
  on public.invoice_payments
  for select
  to authenticated
  using (public.is_active_member());

-- Insert: any active member (staff record payments).
drop policy if exists invoice_payments_insert on public.invoice_payments;
create policy invoice_payments_insert
  on public.invoice_payments
  for insert
  to authenticated
  with check (public.is_active_member());

-- Update: owner + admin only.
drop policy if exists invoice_payments_update on public.invoice_payments;
create policy invoice_payments_update
  on public.invoice_payments
  for update
  to authenticated
  using (
    public.is_active_member()
    and public.get_my_role() in ('owner', 'admin')
  )
  with check (
    public.is_active_member()
    and public.get_my_role() in ('owner', 'admin')
  );

-- Delete: owner + admin only.
drop policy if exists invoice_payments_delete on public.invoice_payments;
create policy invoice_payments_delete
  on public.invoice_payments
  for delete
  to authenticated
  using (
    public.is_active_member()
    and public.get_my_role() in ('owner', 'admin')
  );