-- LabelM — customers table, audit triggers, RLS policies.
--
-- Security model
--   * RLS is enabled; `anon` has no access at all.
--   * Any active member may read/create/update (soft-delete) customers.
--   * Deletes are soft: rows are hidden via deleted_at/deleted_by and every
--     read filters deleted_at is null.
--   * created_by / updated_by are stamped automatically from auth.uid().

-- ---------------------------------------------------------------------------
-- Table
-- ---------------------------------------------------------------------------
create table if not exists public.customers (
  id           integer generated by default as identity primary key,
  name         text not null,
  address      text,
  phone        text,
  email        text,
  gst_number   text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid references public.employees (id) on delete set null,
  updated_by   uuid references public.employees (id) on delete set null,
  deleted_at   timestamptz,
  deleted_by   uuid references public.employees (id) on delete set null
);

create index if not exists customers_name_idx on public.customers (lower(name));
create index if not exists customers_deleted_at_idx on public.customers (deleted_at);

-- ---------------------------------------------------------------------------
-- updated_at maintenance (reuses the shared set_updated_at() trigger)
-- ---------------------------------------------------------------------------
drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at
  before update on public.customers
  for each row
  execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- created_by / updated_by stamping
-- ---------------------------------------------------------------------------
create or replace function public.set_audit_fields()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by = auth.uid();
  end if;
  new.updated_by = auth.uid();
  return new;
end;
$$;

drop trigger if exists customers_set_audit_fields on public.customers;
create trigger customers_set_audit_fields
  before insert or update on public.customers
  for each row
  execute function public.set_audit_fields();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.customers enable row level security;

-- Read: active members see only non-deleted customers.
drop policy if exists customers_select on public.customers;
create policy customers_select
  on public.customers
  for select
  to authenticated
  using (public.is_active_member() and deleted_at is null);

drop policy if exists customers_insert on public.customers;
create policy customers_insert
  on public.customers
  for insert
  to authenticated
  with check (public.is_active_member());

-- Update: active members may edit; soft-delete is a normal update
-- (set deleted_at / deleted_by).
drop policy if exists customers_update on public.customers;
create policy customers_update
  on public.customers
  for update
  to authenticated
  using (public.is_active_member() and deleted_at is null)
  with check (public.is_active_member());

-- Delete: defense-in-depth; the intended path is a soft-delete update above.
drop policy if exists customers_delete on public.customers;
create policy customers_delete
  on public.customers
  for delete
  to authenticated
  using (public.is_active_member());