-- LabelM — labels table, rate lock, audit triggers, RLS policies.
--
-- Design
--   * Labels snapshot rate/amount at creation; they are NOT a live join to
--     customer_prices (added separately). Changing a customer's rate later
--     never rewrites existing labels.
--   * Unbilled labels (invoice_id is null) are editable (the review-before-
--     invoice flow). Billed labels are immutable: the before-update trigger
--     blocks any change once invoice_id is set.
--   * invoice_id is intentionally created WITHOUT a FK for now; the invoices
--     table does not exist yet. The FK will be added in the invoices migration.
--   * Deletes are also blocked once billed (before-delete trigger).

-- ---------------------------------------------------------------------------
-- Table
-- ---------------------------------------------------------------------------
create table if not exists public.labels (
  id          integer generated by default as identity primary key,
  sl_no       text not null unique,
  customer_id integer not null references public.customers (id) on delete restrict,
  label_date  date not null,
  weight      numeric(10,3) not null check (weight > 0),
  rate        numeric(12,2) not null check (rate >= 0),
  amount      numeric(12,2) not null check (amount = round(weight * rate, 2)),
  status      text not null default 'draft' check (status in ('draft', 'printed')),
  invoice_id  integer,
  created_by  uuid references public.employees (id) on delete set null,
  updated_by  uuid references public.employees (id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists labels_customer_idx on public.labels (customer_id, label_date);
create index if not exists labels_invoice_idx on public.labels (invoice_id);
create index if not exists labels_status_idx on public.labels (status);
create index if not exists labels_label_date_idx on public.labels (label_date);

-- ---------------------------------------------------------------------------
-- updated_at maintenance (reuses the shared set_updated_at() trigger)
-- ---------------------------------------------------------------------------
drop trigger if exists labels_set_updated_at on public.labels;
create trigger labels_set_updated_at
  before update on public.labels
  for each row
  execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- created_by / updated_by stamping (reuses the shared set_audit_fields trigger)
-- ---------------------------------------------------------------------------
drop trigger if exists labels_set_audit_fields on public.labels;
create trigger labels_set_audit_fields
  before insert or update on public.labels
  for each row
  execute function public.set_audit_fields();

-- ---------------------------------------------------------------------------
-- Billed labels are immutable
--   * UPDATE: rejected once invoice_id is set (invoice assignment itself is
--     allowed because old.invoice_id is still null at that point).
--   * DELETE: rejected once invoice_id is set.
-- ---------------------------------------------------------------------------
create or replace function public.labels_lock_billed()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if old.invoice_id is not null then
    raise exception 'billed labels cannot be altered' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists labels_lock_billed on public.labels;
create trigger labels_lock_billed
  before update on public.labels
  for each row
  execute function public.labels_lock_billed();

create or replace function public.labels_lock_billed_delete()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if old.invoice_id is not null then
    raise exception 'billed labels cannot be deleted' using errcode = '42501';
  end if;
  return old;
end;
$$;

drop trigger if exists labels_lock_billed_delete on public.labels;
create trigger labels_lock_billed_delete
  before delete on public.labels
  for each row
  execute function public.labels_lock_billed_delete();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.labels enable row level security;

-- Read: any active member.
drop policy if exists labels_select on public.labels;
create policy labels_select
  on public.labels
  for select
  to authenticated
  using (public.is_active_member());

-- Insert: any active member.
drop policy if exists labels_insert on public.labels;
create policy labels_insert
  on public.labels
  for insert
  to authenticated
  with check (public.is_active_member());

-- Update: any active member. The billed-lock trigger above guards immutability.
drop policy if exists labels_update on public.labels;
create policy labels_update
  on public.labels
  for update
  to authenticated
  using (public.is_active_member())
  with check (public.is_active_member());

-- Delete: any active member. The billed-lock trigger guards billed rows.
drop policy if exists labels_delete on public.labels;
create policy labels_delete
  on public.labels
  for delete
  to authenticated
  using (public.is_active_member());