-- LabelM — invoices table, RLS policies, and the deferred labels FK.
--
-- Design
--   * An invoice summarizes the labels billed in a period for one customer.
--     Line items are NOT stored here — they are the labels whose
--     invoice_id points at this row.
--   * total_amount / total_weight are snapshots, consistent with the label
--     snapshot model.
--   * status is maintained by the app when payments are recorded
--     (Paid / Unpaid / Partial).
--   * This migration also adds the FK from labels.invoice_id, which was
--     deliberately deferred until invoices existed.

-- ---------------------------------------------------------------------------
-- Table
-- ---------------------------------------------------------------------------
create table if not exists public.invoices (
  id             integer generated by default as identity primary key,
  invoice_number text not null unique,
  customer_id    integer not null references public.customers (id) on delete restrict,
  period_start   date not null,
  period_end     date not null,
  total_amount   numeric(12,2) not null check (total_amount >= 0),
  total_weight   numeric(12,2) check (total_weight is null or total_weight >= 0),
  status         text not null default 'Unpaid' check (status in ('Paid', 'Unpaid', 'Partial')),
  due_date       date,
  generated_by   uuid references public.employees (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  check (period_end >= period_start)
);

create index if not exists invoices_customer_idx on public.invoices (customer_id, period_start);
create index if not exists invoices_status_idx on public.invoices (status);
create index if not exists invoices_invoice_number_idx on public.invoices (invoice_number);

-- ---------------------------------------------------------------------------
-- updated_at maintenance (reuses the shared set_updated_at() trigger)
-- ---------------------------------------------------------------------------
drop trigger if exists invoices_set_updated_at on public.invoices;
create trigger invoices_set_updated_at
  before update on public.invoices
  for each row
  execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- generated_by stamping on insert
-- ---------------------------------------------------------------------------
create or replace function public.invoices_set_generated_by()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.generated_by = auth.uid();
  return new;
end;
$$;

drop trigger if exists invoices_set_generated_by on public.invoices;
create trigger invoices_set_generated_by
  before insert on public.invoices
  for each row
  execute function public.invoices_set_generated_by();

-- ---------------------------------------------------------------------------
-- Deferred FK: labels.invoice_id now points at invoices.id
-- ---------------------------------------------------------------------------
alter table public.labels
  drop constraint if exists labels_invoice_id_fkey;
alter table public.labels
  add constraint labels_invoice_id_fkey
  foreign key (invoice_id)
  references public.invoices (id)
  on delete set null;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.invoices enable row level security;

-- Read: any active member (staff can view all invoices).
drop policy if exists invoices_select on public.invoices;
create policy invoices_select
  on public.invoices
  for select
  to authenticated
  using (public.is_active_member());

-- Insert: owner + admin only.
drop policy if exists invoices_insert on public.invoices;
create policy invoices_insert
  on public.invoices
  for insert
  to authenticated
  with check (
    public.is_active_member()
    and public.get_my_role() in ('owner', 'admin')
  );

-- Update: any active member (staff record payments → status changes).
drop policy if exists invoices_update on public.invoices;
create policy invoices_update
  on public.invoices
  for update
  to authenticated
  using (public.is_active_member())
  with check (public.is_active_member());

-- Delete: owner + admin only.
drop policy if exists invoices_delete on public.invoices;
create policy invoices_delete
  on public.invoices
  for delete
  to authenticated
  using (
    public.is_active_member()
    and public.get_my_role() in ('owner', 'admin')
  );