-- LabelM — customer_prices table, effective-range guard, audit, RLS.
--
-- Design
--   * One rate per customer at any point in time (single fixed product).
--   * effective_from / effective_to define when a rate applies. Null
--     effective_to = current rate. Non-overlapping ranges per customer are
--     enforced with an exclusion constraint (requires btree_gist).
--   * Labels snapshot their own rate/amount at creation; this table is only
--     the source used to auto-fill new labels (matched on label_date).

-- ---------------------------------------------------------------------------
-- Extension: btree_gist (for the exclusion constraint on date ranges)
-- ---------------------------------------------------------------------------
create extension if not exists btree_gist;

-- ---------------------------------------------------------------------------
-- Table
-- ---------------------------------------------------------------------------
create table if not exists public.customer_prices (
  id             integer generated by default as identity primary key,
  customer_id    integer not null references public.customers (id) on delete cascade,
  rate           numeric(12,2) not null check (rate >= 0),
  effective_from date not null,
  effective_to   date,
  created_by     uuid references public.employees (id) on delete set null,
  updated_by     uuid references public.employees (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  check (effective_to is null or effective_to >= effective_from)
);

-- A customer can have only one active rate at a time (no overlapping ranges).
-- btree_gist makes the integer equality operator usable inside EXCLUDE.
alter table public.customer_prices
  drop constraint if exists customer_prices_no_overlap;
alter table public.customer_prices
  add constraint customer_prices_no_overlap
  exclude using gist (
    customer_id with =,
    daterange(effective_from, coalesce(effective_to, 'infinity'::date)) with &&
  );

create index if not exists customer_prices_customer_idx
  on public.customer_prices (customer_id, effective_from desc);

-- ---------------------------------------------------------------------------
-- created_by / updated_by stamping + updated_at maintenance
-- (reuses the shared set_audit_fields / set_updated_at triggers)
-- ---------------------------------------------------------------------------
drop trigger if exists customer_prices_set_audit_fields on public.customer_prices;
create trigger customer_prices_set_audit_fields
  before insert or update on public.customer_prices
  for each row
  execute function public.set_audit_fields();

drop trigger if exists customer_prices_set_updated_at on public.customer_prices;
create trigger customer_prices_set_updated_at
  before update on public.customer_prices
  for each row
  execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.customer_prices enable row level security;

-- Read: any active member.
drop policy if exists customer_prices_select on public.customer_prices;
create policy customer_prices_select
  on public.customer_prices
  for select
  to authenticated
  using (public.is_active_member());

-- Insert: any active member.
drop policy if exists customer_prices_insert on public.customer_prices;
create policy customer_prices_insert
  on public.customer_prices
  for insert
  to authenticated
  with check (public.is_active_member());

-- Update: any active member.
drop policy if exists customer_prices_update on public.customer_prices;
create policy customer_prices_update
  on public.customer_prices
  for update
  to authenticated
  using (public.is_active_member())
  with check (public.is_active_member());

-- Delete: any active member.
drop policy if exists customer_prices_delete on public.customer_prices;
create policy customer_prices_delete
  on public.customer_prices
  for delete
  to authenticated
  using (public.is_active_member());